//
//  DeleteOrderInteractor.swift
//  CleanStore
//
//  Created by Vladimir Fibe on 06.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DeleteOrderBusinessLogic
{
  func doSomething(request: DeleteOrder.Something.Request)
}

protocol DeleteOrderDataStore
{
  //var name: String { get set }
}

class DeleteOrderInteractor: DeleteOrderBusinessLogic, DeleteOrderDataStore
{
  var presenter: DeleteOrderPresentationLogic?
  var worker: DeleteOrderWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: DeleteOrder.Something.Request)
  {
    worker = DeleteOrderWorker()
    worker?.doSomeWork()
    
    let response = DeleteOrder.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
