//
//  DeleteOrderPresenter.swift
//  CleanStore
//
//  Created by Vladimir Fibe on 06.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DeleteOrderPresentationLogic
{
  func presentSomething(response: DeleteOrder.Something.Response)
}

class DeleteOrderPresenter: DeleteOrderPresentationLogic
{
  weak var viewController: DeleteOrderDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: DeleteOrder.Something.Response)
  {
    let viewModel = DeleteOrder.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
